env:
  browser: true
  es2021: true
  node: true
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
parser: '@typescript-eslint/parser'
ignorePatterns:
  - 'node_modules/*'
  - 'dist/*'
  - 'coverage/*'
  - 'docs/*'
rules: {
  no-var: warn,
  prefer-const: warn,
  no-mixed-spaces-and-tabs: warn,
}
