version: "3.9"

services: 
  api:
    container_name: back_end_api
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    tty: true
    expose:
      - '4000'
    ports: 
      - "4000:4000"
    volumes:
    #-  ./:/usr/src/app/.
    - ./src:/usr/src/app/src  #major
    #- .:/usr/src/app/build #for debugging
    #- ./dist:/usr/src/app/dist # for debugging
    #- ./nodu_modules:/usr/src/app/node_modules #for debugging
    
    networks:
      - empiNetwork
    command: npm run dev
networks:
  empiNetwork:  