version: "3.9"

services: 
  api:
    container_name: back_end_api
    build: 
      context: .
      dockerfile: Dockerfile
      target: base
    tty: true
    expose:
      - '40000'
    ports: 
      - "4000:4000"
    volumes:
    - ./src:/usr/src/app/src
    #- ./build:/usr/src/app/build #for debugging
    networks:
      - empiNetwork
    command: npm run dev
networks:
  empiNetwork:  