version: "3.9"

services:
    api:
        container_name: back_end_api
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        tty: true
        expose:
            - "4000"
        ports:
            - "4000:4000"
        volumes:
            - ./:/usr/src/app/
        networks:
            - empiNetwork
        command: >
            bash -c "yarn db:generate && yarn dev"
    db:
        container_name: back_end_studio
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        env_file:
            - .env
        expose:
            - "5555"
        ports:
            - "5555:5555"
        volumes:
            - ./:/usr/src/app/
        networks:
            - empiNetwork
        command: >
            bash -c "yarn db:studio"
    redis:
        container_name: back_end_redis
        image: redis
        ports:
            - "6379:6379"
        networks:
            - empiNetwork
    redis-insight:
        container_name: back_end_redis_insight
        image: redislabs/redisinsight:latest
        volumes:
            - redisinsight:/db
        ports:
            - "8001:8001"
        networks:
            - empiNetwork
networks:
    empiNetwork:

volumes:
    redisinsight: