version: "3.9"

volumes:
    api_data:

services:
    api:
        container_name: back_end_api
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        tty: true
        expose:
            - "4000"
        ports:
            - "4000:4000"
        volumes:
            - api_data:/usr/src/app/
        networks:
            - empiNetwork
        command: >
            bash -c "yarn db:generate && yarn dev"
networks:
    empiNetwork:
