version: "3.9"

services:
    api:
        container_name: back_end_api
        restart: on-failure
        image: node:latest
        working_dir: /usr/src/app
        env_file:
            - .env
        ports:
            - "4000:4000"
        volumes:
            - ./:/usr/src/app/
        networks:
            - apiNetwork
        command: yarn dev
    studio:
        restart: always
        container_name: back_end_studio
        image: node:latest
        working_dir: /usr/src/app
        env_file:
            - .env
        ports:
            - "5555:5555"
        volumes:
            - ./:/usr/src/app/
        networks:
            - apiNetwork
        command: bash -c "yarn db:studio --browser false"
networks:
    apiNetwork:
        driver: bridge