version: "3.9"

services: 
  api:
    container_name: back_end_api
    build: 
      context: .
    tty: true
    ports: 
      - "4000:4000"
    volumes:
    - .:/usr/src/app/.
    networks:
      - empiNetwork
networks:
  empiNetwork:  