version: "2.1"
orbs:
    node: circleci/node@latest
jobs:
    test:
        executor:
            name: node/default
            tag: "16"
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  command: yarn test
                  name: Run jest tests
workflows:
    test_my_app:
        jobs:
            - test
