version: "2.1"
orbs:
    node: circleci/node@5.0.2
jobs:
    install-node:
        docker:
            - image: "cimg/base:stable"
        steps:
            - checkout
            - node/install:
                  install-yarn: true
                  node-version: "18"
            - run: node --version
    test:
        executor:
            name: node/default
            tag: "16"
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  command: yarn test
                  name: Run jest tests
    cov:
        executor:
            name: node/default
            tag: "16"
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - run:
                  command: yarn test:cov
                  name: Run jest tests with coverage
workflows:
    test_my_app:
        jobs:
            - install-node
            - test
            - cov
